#!/bin/bash
set -e
echo "🚀 Deploying to Hugging Face Spaces..."
echo ""
echo "1. Buat Space di https://huggingface.co/new-space"
echo "   - Name: flowdoro-api"
echo "   - SDK: Docker"
echo "   - Hardware: Free (CPU)"
echo ""
echo "2. Push code ke GitHub"
echo "   git push origin master"
echo ""
echo "3. Hubungkan Space ke repo GitHub"
echo "   Settings → Version Control → Connect to GitHub"
echo ""
echo "4. Set env vars di Settings → Variables and secrets:"
echo "   APPWRITE_ENDPOINT=https://sgp.cloud.appwrite.io/v1"
echo "   APPWRITE_PROJECT_ID=6a97cfd7002c5462242e"  
echo "   APPWRITE_API_KEY=standard_34e6... (→ Secrets!)"
echo "   APPWRITE_DATABASE_ID=6a97dd7e002e7e71c54c"
echo "   NODE_ENV=production"
echo "   PORT=7860"
echo ""
echo "5. Factory reboot di Settings → Hardware"
