name = "flowdoro-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
APP_URL = "https://flowdoro.email-trisno-sanjaya.pages.dev"
CORS_ORIGIN = "https://flowdoro-web.pages.dev"
API_URL = ""
REST_RATIO_DEFAULT = "5"
LOG_LEVEL = "info"
APPWRITE_ENDPOINT = "https://sgp.cloud.appwrite.io/v1"
APPWRITE_PROJECT_ID = "6a97cfd7002c5462242e"
APPWRITE_DATABASE_ID = "6a97dd7e002e7e71c54c"
APPWRITE_COLLECTION_PROFILES = "profiles"
APPWRITE_COLLECTION_TASKS = "tasks"
APPWRITE_COLLECTION_SESSIONS = "sessions"
APPWRITE_COLLECTION_EVENTS = "session_events"
APPWRITE_COLLECTION_LISTS = "lists"
APPWRITE_BUCKET_AVATARS = "avatars"
APPWRITE_API_KEY = "standard_34e65988872a02b7a7cf688d7ac47e0434452975b58ba98bb1fe51b6883f01c3135409446ed7b71420bb038f8c41a06e39d5d8e4e6a5bc971322840f48bb0c8e941b8c60cb64af3ddd3d8cc681825cb0b93f5ec5e4ed732b940dea2f218aa4c95d26754d90676de224a95e4655e52c3c96d0680885cd7e0758cab77deba60c09"
